# Generated by Django 5.1 on 2024-10-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gte', 0)), name='age_gte_0')],
            },
        ),
    ]
