# Generated by Django 5.1 on 2024-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
